name: AI Strategy CI

on: [push, pull_request]

jobs:
  test-ai-system:
    runs-on: ubuntu-latest

    steps:
    - name: Klona repo
      uses: actions/checkout@v3

    - name: Installera Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installera beroenden
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Kör tester
      run: |
        pytest tests/

